# Generated by Django 5.0.6 on 2025-09-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
