# Generated by Django 5.0.6 on 2025-08-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
