# Generated by Django 5.0.6 on 2025-09-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='identificacion',
            field=models.FileField(blank=True, null=True, upload_to='identificaciones/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie_verificacion',
            field=models.ImageField(blank=True, null=True, upload_to='selfies_verificacion/'),
        ),
    ]
